CREATE DATABASE IF NOT EXISTS CRYPTO_TRADING;

USE CRYPTO_TRADING;

-- TABLES STRUCTURES
CREATE TABLE IF NOT EXISTS ASSETS (
	ASSET_NAME			VARCHAR(10) NOT NULL,
	A_CLASS 			VARCHAR(20),
	ALT_NAME			VARCHAR(10),
	DECIMALS			INT,
	DISPLAY_DECIMALS	INT,
	START_TIME			BIGINT      NOT NULL,
	EXPIRE_TIME			BIGINT,
	PRIMARY KEY(ASSET_NAME, START_TIME)
);


CREATE TABLE IF NOT EXISTS ASSET_PAIRS (
	PAIR_ID				BIGINT		AUTO_INCREMENT PRIMARY KEY,
	PAIR_NAME			VARCHAR(20) NOT NULL,
	ALT_NAME			VARCHAR(20),
	A_CLASS_BASE		VARCHAR(20),
	BASE				VARCHAR(10),
	A_CLASS_QUOTE		VARCHAR(20),
	QUOTE				VARCHAR(10),
	LOT					VARCHAR(20),
	PAIR_DECIMALS		INT,
	LOT_DECIMALS		INT,
	LOT_MULTIPLIER		INT,
	FEE_VOLUME_CURRENCY	VARCHAR(20),
	MARGIN_CALL			INT,
	MARGIN_STOP			INT,
	START_TIME			BIGINT,
	EXPIRE_TIME			BIGINT 	
);	
CREATE TABLE IF NOT EXISTS ASSET_PAIRS_FEE (
	PAIR_ID			BIGINT,
	FEE_TYPE		ENUM('fees', 'fees_maker'),
	VOLUME			INT,
	PERCENT_FEE		DECIMAL(10,5)
);
CREATE TABLE IF NOT EXISTS ASSET_PAIRS_LEVERAGE (
	PAIR_ID			BIGINT,
	LEVERAGE_TYPE	ENUM('buy', 'sell'),
	LEVERAGE_VALUE	INT
);


CREATE TABLE IF NOT EXISTS TICKERS (
    CALL_TIME		        BIGINT      NOT NULL,
	PAIR_NAME               VARCHAR(20) NOT NULL,
    ASK_PRICE		        DECIMAL(20,10),
	ASK_WHOLE_LOT_VOLUME    INT,
	ASK_LOT_VOLUME          DECIMAL(20,10),
    BID_PRICE		        DECIMAL(20,10),
	BID_WHOLE_LOT_VOLUME    INT,
	BID_LOT_VOLUME          DECIMAL(20,10),
    LAST_CLOSED_PRICE		DECIMAL(20,10),
	LAST_CLOSED_LOT_VOLUME  DECIMAL(20,10),
    VOLUME_TODAY		    DECIMAL(20,10),
	VOLUME_LAST_24          DECIMAL(20,10),
    VOLUME_WEIGHTED_AVERAGE_TODAY		DECIMAL(20,10),
	VOLUME_WEIGHTED_AVERAGE_LAST_24     DECIMAL(20,10),
    NUMBER_TRADES_TODAY		DECIMAL(20,10),
	NUMBER_TRADES_LAST_24   DECIMAL(20,10),
    LOW_TODAY		        DECIMAL(20,10),
	LOW_LAST_24             DECIMAL(20,10),
    HIGH_TODAY		        DECIMAL(20,10),
	HIGH_LAST_24            DECIMAL(20,10),
	OPENING_PRICE           DECIMAL(20,10),
	GRAFANA_TIME            DATETIME NOT NULL,

	PRIMARY KEY (CALL_TIME, PAIR_NAME)
);


CREATE TABLE IF NOT EXISTS LAST_CALL_TIME (
    ELEM_KEY    VARCHAR(20) NOT NULL,
    METHOD_NAME VARCHAR(20) NOT NULL,
    LAST_TIME   BIGINT      NOT NULL,
    PRIMARY KEY (ELEM_KEY, METHOD_NAME)
);


CREATE TABLE IF NOT EXISTS SPREAD_DATA (
    SPREAD_TIME     BIGINT      NOT NULL,
	PAIR_NAME       VARCHAR(20) NOT NULL,
	BID             DECIMAL(20,10),
	ASK             DECIMAL(20,10),
	PRIMARY KEY(SPREAD_TIME, PAIR_NAME)
);


CREATE TABLE IF NOT EXISTS ACCOUNT_BALANCE (
    CALL_TIME       BIGINT          NOT NULL,
    ASSET_NAME      VARCHAR(10)     NOT NULL,
    BALANCE         DECIMAL(10,10)  NOT NULL,
    PRIMARY KEY(CALL_TIME, ASSET_NAME)
);







