CREATE DATABASE IF NOT EXISTS CRYPTO_TRADING;

USE CRYPTO_TRADING;

-- TABLES STRUCTURES
CREATE TABLE IF NOT EXISTS ASSETS (
	ASSET_NAME			VARCHAR(10) NOT NULL,
	A_CLASS 			VARCHAR(20),
	ALT_NAME			VARCHAR(10),
	DECIMALS			INT,
	DISPLAY_DECIMALS	INT,
	START_TIME			BIGINT      NOT NULL,
	EXPIRE_TIME			BIGINT,
	PRIMARY KEY(ASSET_NAME, START_TIME)
);


CREATE TABLE IF NOT EXISTS ASSET_PAIRS (
	PAIR_ID				BIGINT		AUTO_INCREMENT PRIMARY KEY,
	PAIR_NAME			VARCHAR(20) NOT NULL,
	ALT_NAME			VARCHAR(20),
	A_CLASS_BASE		VARCHAR(20),
	BASE				VARCHAR(10),
	A_CLASS_QUOTE		VARCHAR(20),
	QUOTE				VARCHAR(10),
	LOT					VARCHAR(20),
	PAIR_DECIMALS		INT,
	LOT_DECIMALS		INT,
	LOT_MULTIPLIER		INT,
	FEE_VOLUME_CURRENCY	VARCHAR(20),
	MARGIN_CALL			INT,
	MARGIN_STOP			INT,
	START_TIME			BIGINT,
	EXPIRE_TIME			BIGINT 	
);	
CREATE TABLE IF NOT EXISTS ASSET_PAIRS_FEE (
	PAIR_ID			BIGINT,
	FEE_TYPE		ENUM('fees', 'fees_maker'),
	VOLUME			INT,
	PERCENT_FEE		DECIMAL(4,4)
);
CREATE TABLE IF NOT EXISTS ASSET_PAIRS_LEVERAGE (
	PAIR_ID			BIGINT,
	LEVERAGE_TYPE	ENUM('buy', 'sell'),
	LEVERAGE_VALUE	INT
);


CREATE TABLE IF NOT EXISTS TICKERS (
	ID      		BIGINT		AUTO_INCREMENT PRIMARY KEY,
    CALL_TIME		BIGINT      NOT NULL,
	PAIR_NAME       VARCHAR(20) NOT NULL,
	OPENING_PRICE   DECIMAL(10,10)
);
CREATE TABLE IF NOT EXISTS TICKER_WHOLE_PRICE (
	TICKER_ID		    BIGINT,
    PRICE		        DECIMAL(10,10),
	LOT_VOLUME          DECIMAL(10,5),
	WHOLE_LOT_VOLUME    INT
);
CREATE TABLE IF NOT EXISTS TICKER_PRICE (
	TICKER_ID	BIGINT,
    PRICE		DECIMAL(10,10),
	LOT_VOLUME  DECIMAL(10,5)
);
CREATE TABLE IF NOT EXISTS TICKER_VOLUME (
	TICKER_ID	BIGINT,
    TODAY		DECIMAL(10,10),
	LAST_24     DECIMAL(10,10)
);


CREATE TABLE IF NOT EXISTS SPREAD_DATA (
    SPREAD_TIME     BIGINT      NOT NULL,
	PAIR_NAME       VARCHAR(20) NOT NULL,
	BID             DECIMAL(10,10),
	ASK             DECIMAL(10,10),
	PRIMARY KEY(SPREAD_TIME, PAIR_NAME)
);


CREATE TABLE IF NOT EXISTS ACCOUNT_BALANCE (
    CALL_TIME       BIGINT          NOT NULL,
    ASSET_NAME      VARCHAR(10)     NOT NULL,
    BALANCE         DECIMAL(10,10)  NOT NULL,
    PRIMARY KEY(CALL_TIME, ASSET_NAME)
);







